---
- include: installdocker.yml
- hosts: all

  vars_files:
    - defaults/main.yml

  remote_user: "root"
  become: yes
  gather_facts: no
  serial: 1

  vars_prompt:

    - name: wp_db_name
      prompt: "\n------
              \n\nSpecify WordPress database name"
      private: no
      default: "wordpress"

    - name: wp_db_tb_pre
      prompt: "\n------
              \n\nSpecify WordPress table prefix"
      private: no
      default: "wp_"

    - name: wp_db_psw
      prompt: "\n------
              \n\nSpecify WordPress database password"
      private: yes
      default: "change-M3"
      confirm: yes

  roles:
  - wordpress-docker

